<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a1682cba-a97d-496d-bce4-71868f52c4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6877fbc1-c5e6-4764-8c4f-8abd87c3ea04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/Toolsqa.jpg</value>
      <webElementGuid>fcc2d35a-906a-4323-9d19-68b88bb65b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[1]/a[1]/img[1]</value>
      <webElementGuid>c324ad8d-122f-4954-8a22-1af59cc81e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/a/img</value>
      <webElementGuid>8a8e7286-f61f-4b30-bff4-576e421398a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/img</value>
      <webElementGuid>570c4f9a-5461-4f03-bd17-e48e760c3664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/Toolsqa.jpg']</value>
      <webElementGuid>98292d6d-72c8-4bc8-8bb5-6e84b31ff4de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
