<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Transaksi_v-icon notranslate fas fa-sign-_24d4df</name>
   <tag></tag>
   <elementGuidId>3bcd064d-7ddd-4525-bba8-d055b1e84ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[3]/div/div[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-670']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.fas.fa-sign-in.theme--light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[3]/div/div[2]</value>
      <webElementGuid>1c32a018-87ce-4de7-ac75-d6e95550f038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-670']/div/i</value>
      <webElementGuid>149814ee-213d-407a-a4d2-a77953cc845e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/i</value>
      <webElementGuid>d8f43aa2-5f67-4901-8c89-f0308b1faef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
