<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gaming3</name>
   <tag></tag>
   <elementGuidId>f7c1ceaf-4703-447e-9477-3a6ed2f02746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[2]/div/div[1]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[2]/div/div[1]/div/div</value>
      <webElementGuid>f901ed64-80c8-48d6-be02-75628044b33c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
