<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productCategories</name>
   <tag></tag>
   <elementGuidId>6d9181de-c21e-4603-884d-e9a0d70e10b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/main/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/main/div/div/div[2]</value>
      <webElementGuid>d8160a99-0226-4566-b237-b7ab5e719fad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
